if Code.ensure_loaded?(ExSync) and function_exported?(ExSync, :register_group_leader, 0) do
	ExSync.register_group_leader()
end

alias Zenflows.Ecto.Repo
alias Zenflows.Valflow.{
	Action,
	ActionEnum,
	Agent,
	AgentRelationship,
	AgentRelationshipRole,
	Agreement,
	Appreciation,
	Claim,
	Commitment,
	Comval,
	Duration,
	EconomicEvent,
	EconomicResource,
	EventOrCommitment,
	Fulfillment,
	Geolocation,
	Intent,
	Measure,
	Organization,
	Person,
	Plan,
	Process,
	ProcessSpecification,
	ProductBatch,
	Proposal,
	ProposedIntent,
	ProposedTo,
	RecipeExchange,
	RecipeFlow,
	RecipeProcess,
	RecipeResource,
	ResourceSpecification,
	RoleBehavior,
	Satisfaction,
	Scenario,
	ScenarioDefinition,
	Settlement,
	TimeUnitEnum,
	Unit,
}
